### ISSUE TITLE
Unit lighthouse.service not found.

### ISSUE THREAD

**Issue by jgresham** [diglos/pi-gen#11]
I'm trying to start lighthouse after a fresh install of the eth2 image on a raspi 4, 4GB. After following the README command, I get an error:

```
$ sudo systemctl start lighthouse && sudo systemctl enable lighthouse
Failed to start lighthouse.service: Unit lighthouse.service not found.
```

**Comment by diglos** [comment]
Solved by Twitter.

Lighthouse has 2 services for both Beacon and Validator (lighthouse-beacon and lighthouse-validator)
