### ISSUE TITLE
Update graffana!

### ISSUE THREAD

**Issue by jimjimvalkema** [diglos/pi-gen#15]
I noticed that grafana is outdated when installing a [dashboard ](https://www.reddit.com/r/ethstaker/comments/kbqys4/i_created_a_port_of_the_prysm_dashboard_for/)for my lighthouse validator. 
The latest version is [7.3.5](https://grafana.com/grafana/download?utm_source=grafana_footer&platform=arm) and the one installed is graffana 6.

**Comment by diglos** [comment]
Yes, it is planned for the next release. In the meanwhile, you can do so by typing:

wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
sudo apt-get update
sudo apt-get install grafana

**Comment by jimjimvalkema** [comment]
cool thank you!
