### ISSUE TITLE
 eth1 node using incorrect chain id, 0 != 1

### ISSUE THREAD

**Issue by raffobaffo** [diglos/pi-gen#17]
After manually adding the http flag, the GETH service is up and listening.
```
telnet 127.0.0.1 8545
Trying 127.0.0.1...
Connected to 127.0.0.1.
```

But becon-chain doesn't accept it:
`level=error msg="Could not connect to powchain endpoint" error="could not dial eth1 nodes: eth1 node using incorrect chain id, 0 != 1" prefix=powchain`

**Comment by diglos** [comment]
Hi, Lighthouse Beacon params should be as follows:

beacon --eth1 --http

You can edit /etc/ethereum/lighthouse-beacon.conf.
