### ISSUE TITLE
MONITORING DASHBOARDS

### ISSUE THREAD

**Issue by brwab** [diglos/pi-gen#20]
i have installed the eth2 img.

but my MONITORING DASHBOARDS seams not to work.

i think i have to acces it with:

URL: http://192.168.0.157:3000
User: admin
Password: ethereum

the webpage dose not open..

what can i do about it?

**Comment by diglos** [comment]
Hi,

I'm afraid you are not using the last image. Please, switch to the new repo:

https://github.com/diglos/ethereumonarm

You can follow this instructions:

https://ethereum-on-arm-documentation.readthedocs.io/en/stable/quick-guide/download-and-install.html

**Comment by brwab** [comment]
Thank you now it works
