### ISSUE TITLE
ssh: connect to host <ip> port 22: Connection refused

### ISSUE THREAD

**Issue by wighawag** [diglos/pi-gen#3]
Hi, after setting up my pi with the instruction, I can see it doing some work and even see it on the network,
But I cannot connect to it via ssh.
Any idea ?

**Comment by wighawag** [comment]
I tried adding a `ssh` file without success

**Comment by wighawag** [comment]
I flashed the sd card again and got it working
I remember shuting down the device the first time before it complete so maybe something went wrong then. 
I leave the issue open because maybe it could be more robust

**Comment by diglos** [comment]
Thanks, will take a look.
