### ISSUE TITLE
Add CPU Temp to Grafana

### ISSUE THREAD

**Issue by mondsen** [diglos/pi-gen#6]
I figured it is possible read the PI cpu temp easly. For this Prometheus provides a collector called "thermal_zone" which basically reads from 

/sys/class/thermal/thermal_zone0/temp

I think users would appreciate the CPU temp to estimate wheter CPU throttling is a thing for them. Maybe add even CPU freq?

**Comment by glamperd** [comment]
Prometheus collects CPU temp by default. It's easy to add it to grafana: Add a panel - the metric name is node_hwmon_temp_celsius

**Comment by glamperd** [comment]
...and for CPU frequency, try node_cpu_scaling_frequency_hertz

**Comment by mondsen** [comment]
It seems not on a RPI: 

![2020-08-04 09_51_38-Window](https://user-images.githubusercontent.com/53463563/89268024-40174180-d638-11ea-844f-0f2e07861e42.png)

**Comment by glamperd** [comment]
Oh. On my pi 4 it's there:
![image](https://user-images.githubusercontent.com/5004980/89275457-a2e2fa00-d685-11ea-95ee-cdcf2a0938a8.png)

... and the Prometheus node_exporter doco says its a default metric for Linux: https://github.com/prometheus/node_exporter
Not sure what would account for the variance in your case.

**Comment by diglos** [comment]
Will take a look, thanks for the suggestion.
